### ISSUE TITLE
botnets causing error when viewing scoreboard

### ISSUE THREAD

**Issue by AnarKyx01** [AnarKyx01/RootTheBox#12]
seem'ed to fix when game was reset, but when shutdown and restarted, error returns.

[E 150601 02:32:25 web:1421] Uncaught exception GET /scoreboard/ajax/summary (192.168.1.41)
    HTTPServerRequest(protocol='http', host='192.168.1.205:8888', method='GET', uri='/scoreboard/ajax/summary', version='HTTP/1.1', remote_ip='192.168.1.41', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': '192.168.1.205:8888', 'Accept': '_/_', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.1.205:8888/scoreboard', 'Cookie': '_xsrf=2|0608cdd5|9bec7d1f8d86e555168598f87e6f66c9|1433143359; session_id="2|1:0|10:1433143383|10:session_id|44:MWJhMTViOTRhYmM5OTQyMGM5YjQ0ZDA5Mzc1NDE2ZmY=|ec7e60dddc3d731dad250b450cad3856f231be79255325b4487aa08c7f1b626b"'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1346, in _execute
        result = method(_self.path_args, *_self.path_kwargs)
      File "/home/anarky/PycharmProjects/RootTheBox/handlers/ScoreboardHandlers.py", line 83, in get
        uri[args[0]]()
      File "/home/anarky/PycharmProjects/RootTheBox/handlers/ScoreboardHandlers.py", line 89, in summary_table
        self.render('scoreboard/summary_table.html', teams=Team.ranks())
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 664, in render
        html = self.render_string(template_name, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 771, in render_string
        return t.generate(**namespace)
      File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 278, in generate
        return execute()
      File "scoreboard/summary_table_html.generated.py", line 37, in _tt_execute
        _tt_tmp = BotManager.instance().count_by_team(team)  # scoreboard/summary_table.html:15
      File "/home/anarky/PycharmProjects/RootTheBox/libs/BotManager.py", line 133, in count_by_team
        return len(self.by_team(team))
      File "/home/anarky/PycharmProjects/RootTheBox/libs/BotManager.py", line 130, in by_team
        return [self.botnet[bot.wsock_uuid] for bot in bots]
    KeyError: u'b673ef67-986a-4134-8cba-891ad23ede7a'
[E 150601 02:32:25 BaseHandlers:189] Request from 192.168.1.41 resulted in an error code 500:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1346, in _execute
        result = method(_self.path_args, *_self.path_kwargs)
      File "/home/anarky/PycharmProjects/RootTheBox/handlers/ScoreboardHandlers.py", line 83, in get
        uri[args[0]]()
      File "/home/anarky/PycharmProjects/RootTheBox/handlers/ScoreboardHandlers.py", line 89, in summary_table
        self.render('scoreboard/summary_table.html', teams=Team.ranks())
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 664, in render
        html = self.render_string(template_name, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 771, in render_string
        return t.generate(**namespace)
      File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 278, in generate
        return execute()
      File "scoreboard/summary_table_html.generated.py", line 37, in _tt_execute
        _tt_tmp = BotManager.instance().count_by_team(team)  # scoreboard/summary_table.html:15
      File "/home/anarky/PycharmProjects/RootTheBox/libs/BotManager.py", line 133, in count_by_team
        return len(self.by_team(team))
      File "/home/anarky/PycharmProjects/RootTheBox/libs/BotManager.py", line 130, in by_team
        return [self.botnet[bot.wsock_uuid] for bot in bots]
    KeyError: u'b673ef67-986a-4134-8cba-891ad23ede7a'

**Comment by AnarKyx01** [comment]
Now removing old botnet database on start. Though there is no botnet history(which should be fine as all bots are disconnected if it's not running)
