### ISSUE TITLE
history bug

### ISSUE THREAD

**Issue by AnarKyx01** [AnarKyx01/RootTheBox#4]
This is happening every so often on the backend

[E 150522 11:31:23 ioloop:588] Exception in callback <bound method GameHistory.take_snapshot of <libs.GameHistory.GameHistory object at 0x7f6c05c09750>>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 989, in _run
        return self.callback()
      File "/home/anarky/PycharmProjects/RootTheBox/libs/GameHistory.py", line 75, in take_snapshot
        self.event_manager.push_history(snapshot.to_dict())
    TypeError: push_history() takes exactly 1 argument (2 given)

**Comment by AnarKyx01** [comment]
Fixed this with *arg(Dirty fix?) but appears to work fine, with no errors!
